// data.js
export const fakePetsData = [
  { id: 1, name: "Max", owner: "John", email: "john@example.com" },
  { id: 2, name: "Daisy", owner: "Alice", email: "alice@example.com" },
  { id: 3, name: "Buddy", owner: "Emma", email: "emma@example.com" },
  { id: 4, name: "Charlie", owner: "Michael", email: "michael@example.com" },
  { id: 5, name: "Lucy", owner: "Sophia", email: "sophia@example.com" },
  { id: 6, name: "Bailey", owner: "Olivia", email: "olivia@example.com" },
  { id: 7, name: "Milo", owner: "Liam", email: "liam@example.com" },
  { id: 8, name: "Lola", owner: "Ethan", email: "ethan@example.com" },
  { id: 9, name: "Rocky", owner: "Ava", email: "ava@example.com" },
  { id: 10, name: "Molly", owner: "Isabella", email: "isabella@example.com" },
  { id: 11, name: "Cooper", owner: "Mia", email: "mia@example.com" },
  { id: 12, name: "Lily", owner: "Sophia", email: "sophia@example.com" },
  { id: 13, name: "Oliver", owner: "Aiden", email: "aiden@example.com" },
  { id: 14, name: "Chloe", owner: "Ella", email: "ella@example.com" },
  { id: 15, name: "Bentley", owner: "Jackson", email: "jackson@example.com" },
  { id: 16, name: "Sophie", owner: "Liam", email: "liam@example.com" },
  { id: 17, name: "Tucker", owner: "Lily", email: "lily@example.com" },
  { id: 18, name: "Zoe", owner: "Lucas", email: "lucas@example.com" },
  { id: 19, name: "Ruby", owner: "Aria", email: "aria@example.com" },
  { id: 20, name: "Leo", owner: "Oliver", email: "oliver@example.com" },
  { id: 21, name: "Luna", owner: "Charlotte", email: "charlotte@example.com" },
  { id: 22, name: "Teddy", owner: "Elijah", email: "elijah@example.com" },
  { id: 23, name: "Coco", owner: "Harper", email: "harper@example.com" },
  { id: 24, name: "Zeus", owner: "Emma", email: "emma@example.com" },
  { id: 25, name: "Mia", owner: "Liam", email: "liam@example.com" },
  { id: 26, name: "Rocky", owner: "Ava", email: "ava@example.com" },
  { id: 27, name: "Bailey", owner: "Olivia", email: "olivia@example.com" },
  { id: 28, name: "Charlie", owner: "Michael", email: "michael@example.com" },
  { id: 29, name: "Lucy", owner: "Sophia", email: "sophia@example.com" },
  { id: 30, name: "Max", owner: "John", email: "john@example.com" },
];

export const fakeServicesData = [
  { id: 1, name: "Pet Shower", price: 25.99 },
  { id: 2, name: "Nail Cutting", price: 12.99 },
  { id: 3, name: "Haircut", price: 25.0 },
  { id: 4, name: "Massage", price: 50.0 },
  { id: 5, name: "Pedicure", price: 35.99 },
  { id: 6, name: "Manicure", price: 20.0 },
  { id: 7, name: "Facial", price: 30.5 },
  { id: 8, name: "Waxing", price: 15.75 },
  { id: 9, name: "Eyebrow Threading", price: 10.99 },
  { id: 10, name: "Spa Package", price: 75.0 },
  { id: 11, name: "Body Scrub", price: 40.0 },
  { id: 12, name: "Aromatherapy", price: 18.99 },
  { id: 13, name: "Hot Stone Massage", price: 55.0 },
  { id: 14, name: "Deep Tissue Massage", price: 60.0 },
  { id: 15, name: "Eyelash Extensions", price: 50.99 },
  { id: 16, name: "Tanning Session", price: 22.5 },
  { id: 17, name: "Acupuncture", price: 45.0 },
  { id: 18, name: "Body Wrap", price: 27.99 },
  { id: 19, name: "Foot Massage", price: 17.5 },
  { id: 20, name: "Nail Art", price: 8.99 },
  { id: 21, name: "Hair Coloring", price: 40.0 },
  { id: 22, name: "Hair Styling", price: 30.0 },
  { id: 23, name: "Bikini Wax", price: 25.99 },
  { id: 24, name: "Mud Mask", price: 12.5 },
  { id: 25, name: "Couples Massage", price: 100.0 },
  { id: 26, name: "Teeth Whitening", price: 75.99 },
  { id: 27, name: "Permanent Makeup", price: 55.0 },
  { id: 28, name: "Body Piercing", price: 20.0 },
  { id: 29, name: "Aromatherapy Massage", price: 42.99 },
  { id: 30, name: "Hair Extensions", price: 65.0 },
  { id: 31, name: "Manicure with Gel Polish", price: 25.0 },
  { id: 32, name: "Facial with Extractions", price: 35.0 },
];
